fabrica/fabrica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('gerenciamento.urls')),
    path('', include('gerenciamento.urls_cadastro')),
    path('', include('gerenciamento.urls_visualizacao')),
    path('', include('gerenciamento.urls_relatorios')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

fabrica/gerenciamento/urls.py
from django.urls import path
from .views import (
    master,
    lista_clientes,
    main,
    testing
)

urlpatterns = [
    path('', master, name='master'),
    path('main', main, name='main'),
    path('testing/', testing, name='testing'),

    path('clientes', lista_clientes, name='lista_clientes'),
]

fabrica/gerenciamento/models.py
from django.db import models
from django.utils import timezone

class Cliente(models.Model):
    codigo = models.AutoField(primary_key=True)
    cnpj_cpf = models.CharField(max_length=18, unique=True)
    razao_social = models.CharField(max_length=255)
    nome_fantasia = models.CharField(max_length=255, blank=True, null=True)
    telefone = models.CharField(max_length=15)
    celular = models.CharField(max_length=15)
    email = models.EmailField()
    atividade_economica_profissao = models.CharField(max_length=255)

    def __str__(self):
        nome = self.razao_social
        return nome

class Endereco(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    rua = models.CharField(max_length=50)
    numero = models.CharField(max_length=10)
    complemento = models.CharField(max_length=50, blank=True, null=True)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=50)
    cep = models.CharField(max_length=10)

class Operador(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)
    cargo = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class MaquinaExtrusao(models.Model):
    id = models.AutoField(primary_key=True)
    marca = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)

    def __str__(self):
        nome = self.marca
        return nome

class MaquinaImpressao(models.Model):
    id = models.AutoField(primary_key=True)
    marca = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)

class MaquinaCorte(models.Model):
    id = models.AutoField(primary_key=True)
    marca = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)

class Tratamento(models.Model):
    id = models.AutoField(primary_key=True)
    tratamento_produto = models.CharField(max_length=100)

    def __str__(self):
        return self.tratamento_produto

class Material(models.Model):
    id = models.AutoField(primary_key=True)
    material_produto = models.CharField(max_length=100)

    def __str__(self):
        return self.material_produto

class Acabamento(models.Model):
    id = models.AutoField(primary_key=True)
    acabamento_produto = models.CharField(max_length=100)

    def __str__(self):
        return self.acabamento_produto

class CorProduto(models.Model):
    id = models.AutoField(primary_key=True)
    cor_produto = models.CharField(max_length=100)

    def __str__(self):
        return self.cor_produto

class OrdemServico(models.Model):
    id = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    observacao = models.CharField(max_length=100)
    data_inicio = models.DateField(auto_now_add=True)

    def __str__(self):
        valor = self.id
        nome = f'Orden nº({valor})'
        return nome

class Produto(models.Model):
    ordem_servico = models.ForeignKey(OrdemServico, related_name='produtos', on_delete=models.CASCADE)
    tipo = models.CharField(max_length=100)
    cor_produto = models.ForeignKey(CorProduto, on_delete=models.CASCADE)
    acabamento_produto = models.ForeignKey(Acabamento, on_delete=models.CASCADE)
    tratamento_produto = models.ForeignKey(Tratamento, on_delete=models.CASCADE)
    material_produto = models.ForeignKey(Material, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.tipo
    
class StatusServico(models.Model):
    ordem_servico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    operador = models.ForeignKey(Operador, on_delete=models.CASCADE)
    status = models.CharField(max_length=20)
    hora_alteracao = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateField(auto_now_add=True)

class Tinta(models.Model):
    id = models.AutoField(primary_key=True)
    cor = models.CharField(max_length=50)

class TintaOrdemServico(models.Model):
    id = models.AutoField(primary_key=True)
    ordemservico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    tinta = models.ForeignKey(Tinta, on_delete=models.CASCADE)
    qtde = models.CharField(max_length=10)

class Ingredientes(models.Model):
    id = models.AutoField(primary_key=True)
    ingrediente = models.CharField(max_length=100)

    def __str__(self):
        return self.ingrediente

class IngredienteOrdemServico(models.Model):
    id = models.AutoField(primary_key=True)
    ordemservico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, related_name='ingredientes_ordem_servico', on_delete=models.CASCADE)
    ingrediente = models.ForeignKey(Ingredientes, on_delete=models.CASCADE)
    qtde = models.FloatField()

    def __str__(self):
        ordem = self.ordemservico
        produto_ordem = self.produto
        nome = f'{ordem} - Produto: {produto_ordem}'
        return nome

class Extrusao(models.Model):
    STATUS_CHOICES = [
        ('iniciado', 'Iniciado'),
        ('finalizado', 'Finalizado'),
    ]

    operador = models.ForeignKey(Operador, on_delete=models.CASCADE)
    maquina_extrusao = models.ForeignKey(MaquinaExtrusao, on_delete=models.CASCADE)
    hora_inicio = models.TimeField(null=True, blank=True)
    data_inicio = models.DateField(null=True, blank=True)
    hora_fim = models.TimeField(null=True, blank=True)
    data_fim = models.DateField(null=True, blank=True)
    produto_ingrediente = models.ForeignKey(IngredienteOrdemServico, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='iniciado')
    tipo_produto = models.CharField(max_length=100, null=True, blank=True)
    quantidade = models.FloatField(null=True, blank=True)
    desperdicio = models.FloatField(null=True, blank=True)

    def __str__(self):
        return f"{self.operador} - {self.maquina_extrusao} - {self.produto_ingrediente} - {self.status}"
    
    def save(self, *args, **kwargs):
        # Preenchimento automático de data_inicio e hora_inicio se eles não estiverem definidos
        if self.data_inicio is None:
            self.data_inicio = timezone.localtime().date()
        if self.hora_inicio is None:
            self.hora_inicio = timezone.localtime().time()
        super(Extrusao, self).save(*args, **kwargs)

class Impressao(models.Model):
    ordem_servico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    operador = models.ForeignKey(Operador, on_delete=models.CASCADE)
    maquina_impressao = models.ForeignKey(MaquinaImpressao, on_delete=models.CASCADE)
    hora_inicio = models.DateTimeField()
    hora_fim = models.DateTimeField()
    data = models.DateField()

class Corte(models.Model):
    ordem_servico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    operador = models.ForeignKey(Operador, on_delete=models.CASCADE)
    maquina_corte = models.ForeignKey(MaquinaCorte, on_delete=models.CASCADE)
    hora_inicio = models.DateTimeField()
    hora_fim = models.DateTimeField()
    data = models.DateField()

class ProdutoImpressao(models.Model):
    id = models.AutoField(primary_key=True)
    ordemservico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    item_produzido = models.ForeignKey(Impressao, on_delete=models.CASCADE)
    descricao = models.CharField(max_length=10)
    qtde = models.CharField(max_length=10)
    peso = models.CharField(max_length=10)

class ProdutoCorte(models.Model):
    id = models.AutoField(primary_key=True)
    ordemservico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    item_produzido = models.ForeignKey(Corte, on_delete=models.CASCADE)
    descricao = models.CharField(max_length=10)
    qtde = models.CharField(max_length=10)
    peso = models.CharField(max_length=10)

fabrica/gerenciamento/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import Cliente, Endereco, Operador, MaquinaExtrusao ,MaquinaImpressao ,MaquinaCorte ,Produto ,OrdemServico ,Tinta ,TintaOrdemServico ,Ingredientes ,IngredienteOrdemServico ,Extrusao ,Impressao ,Corte



def master(request):
    template = loader.get_template('base/master.html')
    return HttpResponse(template.render())

def lista_clientes(request):
    clientes = Cliente.objects.all()
    context = {'clientes': clientes}
    return render(request, 'relatorios/clientes.html', context)

def main(request):
    principal = loader.get_template('main.html')
    return HttpResponse(principal.render())

def testing(request):
    template = loader.get_template('template.html')
    context = {
    'fruits': ['Apple', 'Banana', 'Cherry'],   
    }
    return HttpResponse(template.render(context, request))

fabrica/gerenciamento/templates/add/adicionar_cliente.html
{% extends "base/master.html" %}

{% block title %}Adicionar Cliente{% endblock title %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Adicionar Cliente</strong>
            </div>
            <div class="card-body">
                <div>
                    <div class="card-body">
                        <form method="post" id="meuFormulario">
                            {% csrf_token %}
                            <h3>Detalhes do Cliente:</h3>
                            {{ form.as_p }}
                            <h3>Endereço:</h3>
                            {{ endereco_form.as_p }}
                            <input type="submit" value="Enviar">
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>

<script>
jQuery.validator.addMethod("#id_razao_social", function(value, element) {
return this.optional(element) || /^[a-zA-Z]+\s+[a-zA-Z]+(\s+[a-zA-Z]+)*$/.test(value);
}, "Por favor, insira o nome completo");

$('#id_cnpj_cpf').keydown(function(){
    var $this = $(this);
    setTimeout(function(){
        var value = $this.val();
        if (value.length <= 11) {
            $this.mask('000.000.000-009');
        } else {
            $this.mask('00.000.000/0000-00');
        }
    }, 1);
});

$(document).ready(function() {
    $('#id_celular').mask('(00) 00000-0000', {placeholder: "(__) _____-____"});
    $('#id_telefone').mask('(00) 00000-0000', {placeholder: "(__) _____-____"});
    $('#id_cep').mask('00000-000', {placeholder: "_____-___"})
    $('#meuFormulario').validate({
        rules: {
            email: {
                required: true,
                email: true
            },
            telefone: {
                required: false
            },
            atividade_economica_profissao: {
                required: false
            },
            endereco: {
                required: true
            },
            cep: {
                required: false
            }
        },
        
});
})
</script>
{% endblock content %}

fabrica/gerenciamento/templates/add/atualizar_extrusao.html
{% extends "base/master.html" %}

{% block title %}
    Ordens de servico
{% endblock %}

{% block content %}
<section class="row justify-content-center">
    <div class="col-6">
        <h1 class="card-title">Finalizar Extrusão</h1>
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                    {{ form.hora_fim.label_tag }} {{ form.hora_fim }}
                </div>
                <div class="col-6">
                    {{ form.data_fim.label_tag }} {{ form.data_fim }} <br>
                </div>
            </div>
            {{ form.tipo_produto.label_tag }} {{ form.tipo_produto }}<br>
            {{ form.quantidade.label_tag }} {{ form.quantidade }}<br>
            {{ form.desperdicio.label_tag }} {{ form.desperdicio }}<br>
            {{ form.status.label_tag }} {{ form.status }}<br>
            <button class="btn btn-success" type="submit">Atualizar</button>
        </form>
        
        <a class="btn btn-info mt-3" href="{% url 'lista_extrusao' %}">Voltar para a lista de extrusões</a>
    </div>

</section>
{% endblock %}

fabrica/gerenciamento/templates/add/formulario_extrusao.html
{% extends "base/master.html" %}

{% block title %}
    Formulário Extrusao
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Formulário Extrusao</strong>
            </div>
            <div class="card-body">
                <div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.operador.label_tag }} {{ form.operador }}<br>
                            {{ form.maquina_extrusao.label_tag }} {{ form.maquina_extrusao }}<br>
                            {{ form.produto_ingrediente.label_tag }} {{ form.produto_ingrediente }}<br>
                            {{ form.status.label_tag }} {{ form.status }}<br>
                            <input type="submit" value="Submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

fabrica/gerenciamento/templates/add/ingrediente_produto.html
{% extends "base/master.html" %}

{% block title %}Adicionar Produto{% endblock title %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Adicionar Ingredientes de fabricação</strong>
            </div>
            <div class="card-body">
                <div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <label for="ordem_servico">Selecione a Ordem de Serviço:</label>
                            <select class="form-select" id="ordem_servico" name="ordem_servico">
                                {% for ordem in ordens %}
                                    <option value="{{ ordem.id }}">{{ ordem.id }}</option>
                                {% endfor %}
                            </select>
                        
                            <label for="produto">Selecione o Produto:</label>
                            <select class="form-select" id="produto" name="produto">
                                <!-- Opções de produtos serão preenchidas via JavaScript -->
                            </select>
                            <div id="produto-container">
                                <div class="produto-form">
                                    <div class="row">
                                        <div class="col">
                                            {{ form.ingrediente.label_tag }} {{ form.ingrediente }}
                                        </div>
                                        <div class="col">
                                            {{ form.qtde.label_tag }} {{ form.qtde }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="mt-3">
                                <button class="btn btn-info" type="button" id="add-product">+ Ingredientes</button>
                                <input class="btn btn-success" type="submit" value="Salvar">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}
{% block script %}
<script>
    // JavaScript para atualizar a lista de produtos com base na ordem de serviço selecionada
    const ordemServicoSelect = document.getElementById('ordem_servico');
    const produtoSelect = document.getElementById('produto');

    ordemServicoSelect.addEventListener('change', function() {
        const ordemId = this.value;
        fetch(`/api/produtos_por_ordem/${ordemId}/`)
            .then(response => response.json())
            .then(data => {
                let options = '';
                data.forEach(produto => {
                    options += `<option value="${produto.id}">${produto.tipo}</option>`;
                });
                produtoSelect.innerHTML = options;
            });
    });

    let formIdx = 0;
document.addEventListener("DOMContentLoaded", function() {
    const addProductButton = document.getElementById("add-product");
    const productContainer = document.getElementById("produto-container");

    addProductButton.addEventListener("click", function() {
        formIdx++;
        const newProductForm = productContainer.cloneNode(true);
        
        // Atualizar os atributos name e id
        const formFields = newProductForm.querySelectorAll("input, select, textarea");
        formFields.forEach((field) => {
            const oldName = field.getAttribute("name");
            const oldId = field.getAttribute("id");
            if (oldName) {
                field.setAttribute("name", oldName.replace("-0-", `-${formIdx}-`));
            }
            if (oldId) {
                field.setAttribute("id", oldId.replace("-0-", `-${formIdx}-`));
            }
        });

        productContainer.parentNode.appendChild(newProductForm);
    });
});
</script>
{% endblock script %}

fabrica/gerenciamento/templates/add/ingredientes.html
{% extends "base/master.html" %}

{% block title %}Adicionar Produto{% endblock title %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Adicionar Ingredientes</strong>
            </div>
            <div class="card-body">
                <div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h3>Ingredientes</h3>
                            {{ form.as_p }}
                            <input type="submit" value="Enviar">
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

fabrica/gerenciamento/templates/add/ingredientes_extrusao.html
{% extends "base/master.html" %}

{% block title %}
    Formulário Extrusao
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Lista de Ingredientes para produção</strong>
            </div>
            <div class="card-body">
                <div>
                    <div class="card-body">
                        {% for ingrediente in ingredientes %}
                        <p>{{ ingrediente.ingrediente.ingrediente }} - Quantidade: {{ ingrediente.qtde }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

fabrica/gerenciamento/templates/add/maquina_corte.html
{% extends "base/master.html" %}

{% block title %}Adicionar Maquina de Corte{% endblock title %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Adicionar Maquina de Corte</strong>
            </div>
            <div class="card-body">
                <div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h3>Adicionar</h3>
                            {{ form.as_p }}
                            <input type="submit" value="Enviar">
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

fabrica/gerenciamento/templates/add/maquina_extrusao.html
{% extends "base/master.html" %}

{% block title %}Adicionar Maquina de Extrusão{% endblock title %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Adicionar Maquina de Extrusão</strong>
            </div>
            <div class="card-body">
                <div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h3>Adicionar</h3>
                            {{ form.as_p }}
                            <input type="submit" value="Enviar">
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

fabrica/gerenciamento/templates/add/maquina_impressao.html
{% extends "base/master.html" %}

{% block title %}Adicionar Maquina de Impressão{% endblock title %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Adicionar Maquina de Impressão</strong>
            </div>
            <div class="card-body">
                <div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h3>Adicionar</h3>
                            {{ form.as_p }}
                            <input type="submit" value="Enviar">
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

fabrica/gerenciamento/templates/add/operador.html
{% extends "base/master.html" %}

{% block title %}Adicionar Operador{% endblock title %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Adicionar Operador</strong>
            </div>
            <div class="card-body">
                <div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h3>Adicionar</h3>
                            {{ form.as_p }}
                            <input type="submit" value="Enviar">
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

fabrica/gerenciamento/templates/add/ordem_servico.html
{% extends "base/master.html" %}

{% block title %}Adicionar Ordem de serviço{% endblock title %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Adicionar Ordem de Serviço</strong>
            </div>
            <div class="card-body">
                <div>
                    <div class="card-body">
                        <form method="post" id="ordemServicoForm" class="meuFormulario">
                            {% csrf_token %}
                            <h2>Ordem de Serviço</h2>
                            <div class="row">
                                <div class="col">
                                    <h5>Cliente</h5>
                                    {{ ordem_form.cliente }}
                                </div>
                                <div class="col">
                                    <h5>Observação</h5>
                                    {{ ordem_form.observacao }}
                                </div>
                            </div>
                            <div id="produto-container">
                                {{ produto_formset.management_form }}
                                <h2 class="mt-3">Produtos</h2>
                                {% for form in produto_formset %}
                                    <div class="produto-form">
                                        <div class="row">
                                            <div class="col">
                                                {{ form.tipo.label_tag }} {{ form.tipo }}
                                            </div>
                                            <div class="col">
                                                {{ form.cor_produto.label_tag }} {{ form.cor_produto }}
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                {{ form.acabamento_produto.label_tag }} {{ form.acabamento_produto }}
                                            </div>
                                            <div class="col">
                                                {{ form.tratamento_produto.label_tag }} {{ form.tratamento_produto }}
                                            </div>
                                            <div class="col">
                                                {{ form.material_produto.label_tag }} {{ form.material_produto }}
                                            </div>
                                        </div>
                                        <label class="form-check-label">Delete:</label>
                                        <input class="form-check-input" type="checkbox" name="{{ form.prefix }}-DELETE">
                                        <hr class="mb-3">
                                    </div>
                                {% endfor %}
                            </div>
                            <button class="btn btn-info" type="button" id="add-product">+ Produtos</button>
                            <input class="btn btn-success" type="submit" value="Salvar">
                        </form>                     
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>

<script>
document.addEventListener("DOMContentLoaded", function() {
    const addProductButton = document.getElementById("add-product");
    const productContainer = document.getElementById("produto-container");

    addProductButton.addEventListener("click", function() {
        const productForms = document.querySelectorAll(".produto-form");
        const lastProductForm = productForms[productForms.length - 1];
        const newProductForm = lastProductForm.cloneNode(true);

        // Clear the input fields in the cloned form
        const inputs = newProductForm.querySelectorAll("input, select, textarea");
        inputs.forEach(input => {
            input.value = "";
        });

        // Update the TOTAL_FORMS count
        const totalForms = document.getElementById("id_produtos-TOTAL_FORMS");
        const formIdx = parseInt(totalForms.value);
        totalForms.value = formIdx + 1;

        // Update the name and id attributes of the new form fields
        const regex = new RegExp(`-${formIdx - 1}-`, 'g');
        newProductForm.innerHTML = newProductForm.innerHTML.replace(regex, `-${formIdx}-`);

        productContainer.appendChild(newProductForm);
    });
});

    $(document).ready(function() {
        $('#id_datas').mask('00/00/0000', {placeholder: "__/__/____"});
        $('.meuFormulario').validate({
            rules: {
                datas: {
                    required: true,
                },
            },
            messages: {
                datas: {
                    required: "Por favor, insira a data no formato AAAA/MM/DD!",
                },
            },
        });
    });
</script>
    
{% endblock script %}

fabrica/gerenciamento/templates/add/produto.html
{% extends "base/master.html" %}

{% block title %}Adicionar Produto{% endblock title %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Adicionar Produto</strong>
            </div>
            <div class="card-body">
                <div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <h3>Produto</h3>
                            {{ produto_form.tipo.label_tag }} : {{ produto_form.tipo }}
                            {{ produto_form.cor_produto.label_tag }}: {{ produto_form.cor_produto }}
                            {{ produto_form.acabamento_produto.label_tag }}: {{ produto_form.acabamento_produto }}
                            {{ produto_form.tratamento_produto.label_tag }}: {{ produto_form.tratamento_produto }}
                            {{ produto_form.material_produto.label_tag }}: {{ produto_form.material_produto }}
                            <input class="mt-3" type="submit" value="Enviar">
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}