fabrica/fabrica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('gerenciamento.urls')),
    path('', include('gerenciamento.urls_cadastro')),
    path('', include('gerenciamento.urls_visualizacao')),
    path('', include('gerenciamento.urls_relatorios')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

fabrica/gerenciamento/urls.py
from django.urls import path
from .views import (
    master,
    lista_clientes,
    main,
    testing
)

urlpatterns = [
    path('', master, name='master'),
    path('main', main, name='main'),
    path('testing/', testing, name='testing'),

    path('clientes', lista_clientes, name='lista_clientes'),
]

fabrica/gerenciamento/models.py
from django.db import models
from django.utils import timezone

class Cliente(models.Model):
    codigo = models.AutoField(primary_key=True)
    cnpj_cpf = models.CharField(max_length=18, unique=True)
    razao_social = models.CharField(max_length=255)
    nome_fantasia = models.CharField(max_length=255, blank=True, null=True)
    telefone = models.CharField(max_length=15)
    celular = models.CharField(max_length=15)
    email = models.EmailField()
    atividade_economica_profissao = models.CharField(max_length=255)

    def __str__(self):
        nome = self.razao_social
        return nome

class Endereco(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    rua = models.CharField(max_length=50)
    numero = models.CharField(max_length=10)
    complemento = models.CharField(max_length=50, blank=True, null=True)
    cidade = models.CharField(max_length=50)
    estado = models.CharField(max_length=50)
    cep = models.CharField(max_length=10)

class Operador(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=100)
    cargo = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class MaquinaExtrusao(models.Model):
    id = models.AutoField(primary_key=True)
    marca = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)

    def __str__(self):
        nome = self.marca
        return nome

class MaquinaImpressao(models.Model):
    id = models.AutoField(primary_key=True)
    marca = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)

class MaquinaCorte(models.Model):
    id = models.AutoField(primary_key=True)
    marca = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)

class Tratamento(models.Model):
    id = models.AutoField(primary_key=True)
    tratamento_produto = models.CharField(max_length=100)

    def __str__(self):
        return self.tratamento_produto

class Material(models.Model):
    id = models.AutoField(primary_key=True)
    material_produto = models.CharField(max_length=100)

    def __str__(self):
        return self.material_produto

class Acabamento(models.Model):
    id = models.AutoField(primary_key=True)
    acabamento_produto = models.CharField(max_length=100)

    def __str__(self):
        return self.acabamento_produto

class CorProduto(models.Model):
    id = models.AutoField(primary_key=True)
    cor_produto = models.CharField(max_length=100)

    def __str__(self):
        return self.cor_produto

class OrdemServico(models.Model):
    id = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    observacao = models.CharField(max_length=100)
    data_inicio = models.DateField(auto_now_add=True)

    def __str__(self):
        valor = self.id
        nome = f'Orden nº({valor})'
        return nome

class Produto(models.Model):
    ordem_servico = models.ForeignKey(OrdemServico, related_name='produtos', on_delete=models.CASCADE)
    tipo = models.CharField(max_length=100)
    cor_produto = models.ForeignKey(CorProduto, on_delete=models.CASCADE)
    acabamento_produto = models.ForeignKey(Acabamento, on_delete=models.CASCADE)
    tratamento_produto = models.ForeignKey(Tratamento, on_delete=models.CASCADE)
    material_produto = models.ForeignKey(Material, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.tipo
    
class StatusServico(models.Model):
    ordem_servico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    operador = models.ForeignKey(Operador, on_delete=models.CASCADE)
    status = models.CharField(max_length=20)
    hora_alteracao = models.DateTimeField(auto_now_add=True)
    data_alteracao = models.DateField(auto_now_add=True)

class Tinta(models.Model):
    id = models.AutoField(primary_key=True)
    cor = models.CharField(max_length=50)

class TintaOrdemServico(models.Model):
    id = models.AutoField(primary_key=True)
    ordemservico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    tinta = models.ForeignKey(Tinta, on_delete=models.CASCADE)
    qtde = models.CharField(max_length=10)

class Ingredientes(models.Model):
    id = models.AutoField(primary_key=True)
    ingrediente = models.CharField(max_length=100)

    def __str__(self):
        return self.ingrediente

class IngredienteOrdemServico(models.Model):
    id = models.AutoField(primary_key=True)
    ordemservico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, related_name='ingredientes_ordem_servico', on_delete=models.CASCADE)
    ingrediente = models.ForeignKey(Ingredientes, on_delete=models.CASCADE)
    qtde = models.FloatField()

    def __str__(self):
        ordem = self.ordemservico
        produto_ordem = self.produto
        nome = f'{ordem} - Produto: {produto_ordem}'
        return nome

class Extrusao(models.Model):
    STATUS_CHOICES = [
        ('iniciado', 'Iniciado'),
        ('finalizado', 'Finalizado'),
    ]

    operador = models.ForeignKey(Operador, on_delete=models.CASCADE)
    maquina_extrusao = models.ForeignKey(MaquinaExtrusao, on_delete=models.CASCADE)
    hora_inicio = models.TimeField(null=True, blank=True)
    data_inicio = models.DateField(null=True, blank=True)
    hora_fim = models.TimeField(null=True, blank=True)
    data_fim = models.DateField(null=True, blank=True)
    produto_ingrediente = models.ForeignKey(IngredienteOrdemServico, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='iniciado')
    tipo_produto = models.CharField(max_length=100, null=True, blank=True)
    quantidade = models.FloatField(null=True, blank=True)
    desperdicio = models.FloatField(null=True, blank=True)

    def __str__(self):
        return f"{self.operador} - {self.maquina_extrusao} - {self.produto_ingrediente} - {self.status}"
    
    def save(self, *args, **kwargs):
        # Preenchimento automático de data_inicio e hora_inicio se eles não estiverem definidos
        if self.data_inicio is None:
            self.data_inicio = timezone.localtime().date()
        if self.hora_inicio is None:
            self.hora_inicio = timezone.localtime().time()
        super(Extrusao, self).save(*args, **kwargs)

class Impressao(models.Model):
    ordem_servico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    operador = models.ForeignKey(Operador, on_delete=models.CASCADE)
    maquina_impressao = models.ForeignKey(MaquinaImpressao, on_delete=models.CASCADE)
    hora_inicio = models.DateTimeField()
    hora_fim = models.DateTimeField()
    data = models.DateField()

class Corte(models.Model):
    ordem_servico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    operador = models.ForeignKey(Operador, on_delete=models.CASCADE)
    maquina_corte = models.ForeignKey(MaquinaCorte, on_delete=models.CASCADE)
    hora_inicio = models.DateTimeField()
    hora_fim = models.DateTimeField()
    data = models.DateField()

class ProdutoImpressao(models.Model):
    id = models.AutoField(primary_key=True)
    ordemservico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    item_produzido = models.ForeignKey(Impressao, on_delete=models.CASCADE)
    descricao = models.CharField(max_length=10)
    qtde = models.CharField(max_length=10)
    peso = models.CharField(max_length=10)

class ProdutoCorte(models.Model):
    id = models.AutoField(primary_key=True)
    ordemservico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    item_produzido = models.ForeignKey(Corte, on_delete=models.CASCADE)
    descricao = models.CharField(max_length=10)
    qtde = models.CharField(max_length=10)
    peso = models.CharField(max_length=10)

fabrica/gerenciamento/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import Cliente, Endereco, Operador, MaquinaExtrusao ,MaquinaImpressao ,MaquinaCorte ,Produto ,OrdemServico ,Tinta ,TintaOrdemServico ,Ingredientes ,IngredienteOrdemServico ,Extrusao ,Impressao ,Corte



def master(request):
    template = loader.get_template('base/master.html')
    return HttpResponse(template.render())

def lista_clientes(request):
    clientes = Cliente.objects.all()
    context = {'clientes': clientes}
    return render(request, 'relatorios/clientes.html', context)

def main(request):
    principal = loader.get_template('main.html')
    return HttpResponse(principal.render())

def testing(request):
    template = loader.get_template('template.html')
    context = {
    'fruits': ['Apple', 'Banana', 'Cherry'],   
    }
    return HttpResponse(template.render(context, request))

fabrica/gerenciamento/templates/visualizacao/cliente.html
{% extends "base/master.html" %}

{% block title %}
    Lista de Clientes
{% endblock %}

{% block content %}
<section>
    <h1 class="card-title">Clientes</h1>
    <table class="table table-secondary table-striped">
        <tr>
            <th scope="col">#</th>
            <th scope="col">CNPJ/CPF</th>
            <th scope="col">Razão Social</th>
            <th scope="col">Nome Fantasia</th>
            <th scope="col">Celular</th>
            <th scope="col">Email</th>
            <th scope="col">Atividade Econômica/Profissão</th>
            <th scope="col">Endereço</th>
        </tr>
        {% for cliente in cliente %}
        <tr>
            <td>{{ cliente.codigo }}</td>
            <td>{{ cliente.cnpj_cpf }}</td>
            <td>{{ cliente.razao_social }}</td>
            <td>{{ cliente.nome_fantasia }}</td>
            <td>{{ cliente.celular }}</td>
            <td>{{ cliente.email }}</td>
            <td>{{ cliente.atividade_economica_profissao }}</td>
            {% for endereco in cliente.endereco_set.all %}
            <td>{{ endereco.rua }}, {{ endereco.numero }} - {{ endereco.cidade }}, {{ endereco.estado }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>

</section>
{% endblock %}

fabrica/gerenciamento/templates/visualizacao/lista_extrusao.html
{% extends "base/master.html" %}

{% block title %}
    Ordens de servico
{% endblock %}

{% block content %}
<section class="col-12">
    <h1 class="card-title">Lista extruões</h1>
    <table class="table table-secondary table-striped">
        <tr>
            <th scope="col">
                Produtos para serem atualizados
            </th>
        </tr>
        {% for extrusao_p in extrusao %}
        <tr>
            <td>
                {{ extrusao_p }}
                <a class="btn btn-info ms-5" href="{% url 'atualizar_extrusao' extrusao_p.id %}">Atualizar</a><br>
            </td>
        </tr>
        {% endfor %}
    </table>
</section>
{% endblock %}

fabrica/gerenciamento/templates/visualizacao/ordens_servico.html
{% extends "base/master.html" %}

{% block title %}
    Ordens de servico
{% endblock %}

{% block content %}
<section class="col-12">
    <h1 class="card-title">Ordens de servico</h1>
    <table class="table table-secondary table-striped">
        <tr>
            <th scope="col">id</th>
            <th scope="col">Cliente</th>
            <th scope="col">Data Criação</th>
            <th scope="col">Produto</th>
            <th scope="col">Observação</th>
        </tr>
        {% for ordem in ordens %}
        <tr>
            <td>{{ ordem.id }}</td>
            <td>{{ ordem.cliente }}</td>
            <td>{{ ordem.data_inicio }}</td>
            <td> 
            {% for produto in ordem.produtos.all %}
            <!-- Display fields from Produto -->
            {{ produto.tipo }}, {{ produto.cor_produto }}, {{ produto.acabamento_produto }}, {{ produto.tratamento_produto }}, {{ produto.material_produto }}<br>
            {% endfor %}
            </td>
            <td>{{ ordem.observacao }}</td>

        </tr>
        {% endfor %}
    </table>

</section>
{% endblock %}

fabrica/gerenciamento/templates/visualizacao/processo_extrusao.html
{% extends "base/master.html" %}

{% block title %}
    Extrusao
{% endblock %}

{% block content %}
<section class="col-12">
    <h1 class="card-title">Lista extrusões</h1>
    <table class="table table-secondary table-striped">
        <tr>
            <th scope="col">Operador</th>
            <th scope="col">Maquina_extrusao</th>
            <th scope="col">Hora_inicio</th>
            <th scope="col">Data_inicio</th>
            <th scope="col">Hora_fim</th>
            <th scope="col">Data_fim</th>
            <th scope="col">Produto_ingrediente</th>
            <th scope="col">Tipo_produto</th>
            <th scope="col">Quantidade</th>
            <th scope="col">Desperdicio</th>
            <th scope="col">Status</th>
        </tr>
        {% for extrusao_p in extrusao %}
        <tr>
            <td>{{ extrusao_p.operador}}</td>
            <td>{{ extrusao_p.maquina_extrusao}}</td>
            <td>{{ extrusao_p.hora_inicio}}</td>
            <td>{{ extrusao_p.data_inicio}}</td>
            <td>{{ extrusao_p.hora_fim}}</td>
            <td>{{ extrusao_p.data_fim}}</td>
            <td>{{ extrusao_p.produto_ingrediente}}</td>
            <td>{{ extrusao_p.tipo_produto}}</td>
            <td>{{ extrusao_p.quantidade}}</td>
            <td>{{ extrusao_p.desperdicio}}</td>
            <td>{{ extrusao_p.status}}</td>
        </tr>
        {% endfor %}
    </table>
</section>
{% endblock %}

fabrica/gerenciamento/templates/visualizacao/produtos.html
{% extends "base/master.html" %}

{% block title %}
    Lista de Produtos
{% endblock %}

{% block content %}
<section>
    <h1 class="card-title">Produtos</h1>
    <table class="table table-secondary table-striped">
        <tr>
            <th scope="col">id</th>
            <th scope="col">tipo</th>
            <th scope="col">cor_produto</th>
            <th scope="col">acabamento_produto</th>
            <th scope="col">tratamento_produto</th>
            <th scope="col">material_produto</th>
        </tr>
        {% for produto in produtos %}
        <tr>
            <td>{{ produto.id }}</td>
            <td>{{ produto.tipo }}</td>
            <td>{{ produto.cor_produto.cor_produto }}</td>
            <td>{{ produto.acabamento_produto.acabamento_produto }}</td>
            <td>{{ produto.tratamento_produto.tratamento_produto }}</td>
            <td>{{ produto.material_produto.material_produto }}</td>
        </tr>
        {% endfor %}
    </table>

</section>
{% endblock %}